name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # This allows the 20MB engine file to upload

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Tells GitHub to look at your main folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        id: deployment
        uses: actions/deploy-pages@v4
